<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
		<Protobuf Include="Protos\mathOperations.proto" GrpcServices="Server" />
		<Protobuf Include="Protos\rudimentaryService.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\GrpcGreeper.ShareableSdk\GrpcGreeper.ShareableSdk.csproj" />
	</ItemGroup>

</Project>
